import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          WelcomePage(),
        ]),
      ),
    );
  }
}

class WelcomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 850,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 130,
                top: 840,
                child: Container(
                  width: 134,
                  height: 5,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 105,
                top: 796,
                child: Text(
                  'Version 1.0\nBy Kelompok 3 SI Capstone C',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black.withValues(alpha: 0.50),
                    fontSize: 13,
                    fontFamily: 'Funnel Display',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 606.43,
                child: Container(
                  width: 313,
                  height: 46.22,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 2.66,
                        color: const Color(0xFF5F9C3F) /* Hijau-Utama */,
                      ),
                      borderRadius: BorderRadius.circular(8.87),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 8.87,
                        offset: Offset(0, 4.43),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8.87,
                    children: [
                      Text(
                        'Saya sudah punya akun',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 17.73,
                          fontFamily: 'Funnel Display',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 547,
                child: Container(
                  width: 313,
                  height: 46.22,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF7BB662) /* Hijau-Sekunder */,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8.87),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 8.87,
                        offset: Offset(0, 4.43),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8.87,
                    children: [
                      Text(
                        'Saya pengguna baru',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 17.73,
                          fontFamily: 'Funnel Display',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 368,
                child: Container(
                  width: 159,
                  height: 95,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/159x95"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 86,
                top: 330,
                child: SizedBox(
                  width: 220,
                  child: Text(
                    'NutriLink x',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF5F9C3F) /* Hijau-Utama */,
                      fontSize: 32,
                      fontFamily: 'Funnel Display',
                      fontWeight: FontWeight.w700,
                      height: 0.94,
                      letterSpacing: 1,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 86,
                top: 111,
                child: Container(
                  width: 220,
                  height: 210,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 220,
                          height: 210,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/220x210"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 0,
                child: Container(
                  width: 390,
                  height: 38,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 390,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: double.infinity,
                                height: 38,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(
                                  color: Colors.white.withValues(alpha: 0.20),
                                ),
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 30,
                                      top: 7,
                                      child: Container(
                                        width: 54,
                                        height: 21,
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(24),
                                          ),
                                        ),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 1,
                                              child: SizedBox(
                                                width: 54,
                                                height: 20,
                                                child: Text(
                                                  '9:41',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF010101),
                                                    fontSize: 17,
                                                    fontFamily: 'SF Pro Text',
                                                    fontWeight: FontWeight.w600,
                                                    height: 1.29,
                                                    letterSpacing: -0.41,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}