// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-owidYkmpK38HP2doeVR09PFMWo2lt_I',
    appId: '1:1599486853:web:4eeb171338c8e72c5b62ec',
    messagingSenderId: '1599486853',
    projectId: 'nutrilink-5f07f',
    authDomain: 'nutrilink-5f07f.firebaseapp.com',
    storageBucket: 'nutrilink-5f07f.firebasestorage.app',
    measurementId: 'G-V2X2BZSDD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6m7AS7ZL-1v3HCjCTMkygGFIk2Aihqr4',
    appId: '1:1599486853:android:d69e3594599b5a0f5b62ec',
    messagingSenderId: '1599486853',
    projectId: 'nutrilink-5f07f',
    storageBucket: 'nutrilink-5f07f.firebasestorage.app',
  );
}
